version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # root 비밀번호 설정
      MYSQL_DATABASE: ${MYSQL_DATABASE}            # 기본 데이터베이스 생성
      MYSQL_USER: ${MYSQL_USER}                    # 일반 사용자 생성
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - haru-network
    volumes:
      - mysql-data:/var/lib/mysql  # 데이터 볼륨 추가

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - haru-network

networks:
  haru-network:
    driver: bridge

volumes:
  mysql-data: