FROM openjdk:17 AS builder
RUN microdnf install findutils
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src
RUN chmod +x ./gradlew
RUN ./gradlew bootJAR

FROM openjdk:17
COPY --from=builder build/libs/*.jar app.jar